name: qnlp-ws
channels:
  - conda
  - quantum-engineering
dependencies:
  - python=3.8
  - pandas=1.3.3
  - matplotlib=3.4.2
  - qsharp=0.18.2109.162713
  - ipywidgets=7.6.5
  - jupyter=1.0.0
  - scikit-learn=0.24.2
  - pip=21.2.4
  - pip:
       - discopy==0.3.7
       - geneticalgorithm==1.0.2
       - pytket==0.8.0
       - pytket-qiskit==0.8.0
       - qiskit==0.23.6
       - seaborn==0.11.1
       - wikipedia2vec==1.0.5
       - qutip==4.6.2
       - itables
